In [1]:
import pickle

In [2]:
filepath = "/home/ogech/modulation_classification_using_early_exiting/Data/RML22.pickle.01A"

with open(filepath, "rb") as f:
    data = pickle.load(f, encoding="latin1")

In [3]:
print("Number of examples:", len(data.keys()))

Number of examples: 210


In [4]:
modulations = [lst[0] for lst in data.keys()]
snrs = [lst[1] for lst in data.keys()]

In [5]:
import numpy as np

In [6]:
unique_modulations = np.unique(modulations)

print("Number of classifications:", len(unique_modulations))
print("Classifications:\n\t", "\n\t".join(unique_modulations))

Number of classifications: 10
Classifications:
	 8PSK
	AM-DSB
	BPSK
	CPFSK
	GFSK
	PAM4
	QAM16
	QAM64
	QPSK
	WBFM


In [7]:
np.unique(snrs)  # -20 to 20 in steps of 2

array([-20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   0,   2,   4,
         6,   8,  10,  12,  14,  16,  18,  20])

Distribution of classes

In [8]:
for mod in unique_modulations:
    print(mod, len([m for m in modulations if m == mod]))

8PSK 21
AM-DSB 21
BPSK 21
CPFSK 21
GFSK 21
PAM4 21
QAM16 21
QAM64 21
QPSK 21
WBFM 21


In [9]:
# using stratifiedShuffleSplit form scikit-learn - it is a combination of StratifiedKFold and ShuffleSplit

# as a cross-validation object, it ensures the folds are made by preserving the percentage of samples for each class
# let's visualize the behaviour of different cross-validation strategies

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

from sklearn.model_selection import (
    GroupKFold,
    GroupShuffleSplit,
    KFold,
    ShuffleSplit,
    StratifiedGroupKFold,
    StratifiedKFold,
    StratifiedShuffleSplit,
    TimeSeriesSplit,
)

In [10]:
rand_gen = np.random.RandomState(42)
cmap_data = plt.cm.Paired
cmap_cv = plt.cm.coolwarm
nsplits = 4

In [11]:
npoints = 100
x = rand_gen.randn(npoints)

In [14]:
percentiles_classes = [0.1, 0.3, 0.6]
y = np.hstack([[ii] * int(npoints * perc)
              for ii, perc in enumerate(percentiles_classes)])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
grp_priors = rand_gen.dirichlet([2] * 10)
grp_priors

array([0.02150466, 0.05961179, 0.07408155, 0.11334972, 0.10209648,
       0.07940384, 0.01081203, 0.08244781, 0.08815254, 0.36853958])

In [17]:
grps = np.repeat(np.arange(10), rand_gen.multinomial(npoints, grp_priors))
grps

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])